### PR TITLE
Unid 4

### PR DESCRIPTION
**Pull request by pivonne**
Unit 4

### CODE REVIEW

**Comment by jcromerohdz** [comment]
Hello @pivonne and @anahi0621 please fix this conflicts in order to continue with review of you work

**Comment by anahi0621** [comment]
# Data Mining
In this unit we work with the evaluative activity
 [Evaluation unit](https://github.com/pivonne/Mineria-de-datos/tree/Unid_4/Evaluation)

**Comment by anahi0621** [comment]
listo profe.


https://github.com/pivonne/Mineria-de-datos/pull/4

**Comment by jcromerohdz** [comment]
Thanks for fixing the issue, now you can merge into development

**Pull request merged**
