### PR TITLE
Unid 3

### PR DESCRIPTION
**Pull request by pivonne**
Unit number 3 is entered where machine learning practices of different types of regressions are annexed

### CODE REVIEW

**Comment by anahi0621** [comment]
# Data Mining

 >## UNIT 3
>> * [PRACTICE 1 ]()
>> * [PRACTICE 1 ]()
https://github.com/pivonne/Mineria-de-datos/tree/Unid_3/Practices/Practice01

>> * [EXAM ](https://github.com/pivonne/Mineria-de-datos/tree/Unid_2/Evaluation2)

**Comment by anahi0621** [comment]
>> * [PRACTICE 1 ](https://github.com/pivonne/Mineria-de-datos/tree/Unid_3/Practices/Practice01)

>> * [PRACTICE 2 ](https://github.com/pivonne/Mineria-de-datos/tree/Unid_3/Practices/Practice02)

>> * [PRACTICE 3 ](https://github.com/pivonne/Mineria-de-datos/tree/Unid_3/Practices/Practice3)

>> * [PRACTICE 4 ](https://github.com/pivonne/Mineria-de-datos/tree/Unid_3/Practices/Practice4)

>>* [EXAM ](https://github.com/pivonne/Mineria-de-datos/tree/Unid_3/EvaluationU3)

**Comment by anahi0621** [comment]
Professor, in this unit we had a conflict in putting the menu in another README, and we put it that way in the comment.

**Comment by jcromerohdz** [comment]
Nice Job! guys @pivonne and @anahi0621 please merge this branch into development

**Pull request merged**
